spring:
  datasource:
      name: dev
      url: jdbc:mysql://47.93.16.97:3306/wechat?&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      logSlowSql: true
  redis:
    lettuce:
      pool:
        max-active: 15
        max-idle: 15
        min-idle: 15
    host: 47.93.16.97
    port: 6379
server:
  port: 8000

mybatis:
    type-aliases-package: com.github.xaidanwang.zhengke.auth.dao
    type-handlers-package: com.github.xaidanwang.zhengke.auth.typehandler
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
    mapper-locations: "classpath*:mapper/*.xml"

logback:
  appname: zhengke-auth
  logdir: /var/log



